### ISSUE TITLE
Application context from another module

### ISSUE THREAD

**Issue by IgorGanapolsky** [techyourchance/dependency-injection-in-android-course#1]
Hello,
I am currently viewing your course on Udemy (good job on that).  I have a question - if my project consists of many Gradle modules, and only one module is an Android Application Module, then how can I get context reference to my other modules?  I ask because your example (and 99% examples online) only demo a single Gradle module application.  But in the real world, a business may make use of many modules in their apps...

**Comment by techyourchance** [comment]
Hello Igor,
Thank you for reaching out.
At this stage I'm gathering the initial feedback about the course. Then I will start expanding the course with a content that most students will be interested in.

Said all that, I think that I will not answer this one specific question in the course the way you would like it to be answered. Let me explain what I mean.

Dependency injection is an application level architectural pattern and dependency injection frameworks are application level tools. In the most general case of a library project, this project should not depend on the specifics of the application it will be used in.

For a more detailed discussion of what libraries/frameworks should do in order to be compatible with DI you can read these posts by Mark Seemann:
[DI Friendly Library](http://blog.ploeh.dk/2014/05/19/di-friendly-library/)
[DI Friendly Framework](http://blog.ploeh.dk/2014/05/19/di-friendly-framework/)

Now let's get to Android gradle modules specifically.

To my best knowledge, there are two reasons for segregation of Android project into different Gradle modules (these reasons are not mutually exclusive):

1. Improve build times
2. Define clear ownership boundaries between different teams

However, even though the motivation for "Gradle modularization" is similar across many (most?) Android projects, the implementation details vary considerably depending on the specific constraints faced by individual projects.

The team might decide to treat gradle sub-modules as proper library/framework projects (potentially further sub-divided into pure Java and Android), or extension of the original app, or some other scheme.

For example, IMHO, proper modularization strategy should account for [lack of Gradle's support for incremental builds in presence of annotations processors](https://github.com/gradle/gradle/issues/1320) (in this context, the usage of Dagger in gradle sub-modules might be questioned). Therefore, this strategy might depend on the specific third party libraries that are being used on a project.

And that's just the tip of the iceberg.

So, application modularization is a very advanced topic and modularized applications might be exposed to vastly different constraints, which leads to unique ad-hoc implementations being rolled out.

Therefore, I don't think it is possible to give any general advice in respect to dependency injection inside different gradle modules.

**Comment by IgorGanapolsky** [comment]
Thanks for the informative explanation!
